In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("E:/projects/Evraz_haha/exgauster_data_3_weeks.csv",skiprows=None)
df.drop (index = df.index[0],axis = 0, inplace= True)
df.columns = ['№','signal','value']
df

             №               signal                       value
1          0.0               moment  2023-01-25T06:32:25.125007
2          1.0   SM_Exgauster\[0:0]          1.2847222089767456
3          2.0   SM_Exgauster\[0:1]           1.689814805984497
4          3.0   SM_Exgauster\[0:2]          0.9646211862564087
5          4.0   SM_Exgauster\[0:3]          1.6145832538604736
...        ...                  ...                         ...
1912498  561.0  SM_Exgauster\[3:80]                         0.0
1912499  562.0  SM_Exgauster\[3:81]                        65.0
1912500  563.0  SM_Exgauster\[3:82]                        65.0
1912501  564.0  SM_Exgauster\[3:83]                        65.0
1912502  565.0  SM_Exgauster\[3:84]                        65.0

[1912502 rows x 3 columns]

In [10]:
df_dict = df.to_dict()
replacements_dict = replacements.to_dict()
for i in df_dict:
     if i in replacements:
        df_dict[replacements[i]] = df_dict.pop(i)

df_dict

NameError: name 'replacements' is not defined

In [9]:
df[df['signal'].str.contains(r'\bmoment')]

           №  signal                       value
1        0.0  moment  2023-01-25T06:32:25.125007
767      0.0  moment  2023-01-25T06:33:25.125007
1533     0.0  moment  2023-01-25T06:34:25.125007
2299     0.0  moment  2023-01-25T06:35:25.125007
3065     0.0  moment  2023-01-25T06:36:25.125007
...      ...     ...                         ...
1908873  0.0  moment  2023-01-27T00:42:25.125007
1909639  0.0  moment  2023-01-27T00:43:25.125007
1910405  0.0  moment  2023-01-27T00:44:25.125007
1911171  0.0  moment  2023-01-27T00:45:25.125007
1911937  0.0  moment  2023-01-27T00:46:25.125007

[2497 rows x 3 columns]